### ISSUE TITLE
Unnecessary duplication of algebraPreCalc

### ISSUE THREAD

**Issue by aneziac** [wmboyles/Math-Summaries#34]
I've noticed that both `diffEq` and `calc` have the same algebraPreCalc directory with minor structural differences. It would probably be better to host the directory in one or the other. However, as more subjects are added to the repo, the overlap problem will only get worse. It might be a good idea to create a `shared` folder for common math concepts.

**Comment by wmboyles** [comment]
This was something I was thinking about earlier myself. I'd like to separate out the background and review chapters as much as possible. Ideally, all background and review material could be in a `shared` folder, maybe along with `contributors.tex`, and each work could have a single tex file that includes just the sections of background and review it needs.

For example, all of the works would include a review of algebra and precalculus, but only `diffEq` and `multiCalc` would include a review of single-variable calculus.

If you'd like to take a shot at it, please do. Otherwise, I'll probably try to do it, likely creating a separate branch.

**Comment by aneziac** [comment]
Ok. I'll do my best at tackling this.
